### ISSUE TITLE
Should `no_record` be set to TRUE as default?

### ISSUE THREAD

**Issue by charliejhadley** [ropensci/opencage#108]
In OpenCage's page about GDPR (https://opencagedata.com/gdpr) users are encouraged to set no_record as TRUE

> While you should only ever be sending us geographic data and NOT personal data, if you use the optional no_record parameter we will not store your query in our logs. In this case we have no record of what the query was. **We encourage you to use this parameter.**

Should `no_record` be set as TRUE by default within the package?

**Comment by dpprdan** [comment]
While I am sympathetic to the idea, my guess would be that no one would turn `no_record` back to `FALSE`, which would imply that OpenCage would not get any query data from R users. How important is this data for improving the API, @freyfogle?

I would think that we encourage users in the package documentation and vignettes to use the parameter as well.

**Comment by freyfogle** [comment]
Totally up to you, makes no difference for us. thanks for asking though

**Comment by dpprdan** [comment]
`no_record` is now set to `TRUE` by default. Thank you very much for the suggestion, @charliejhadley! 🎉
