### ISSUE TITLE
integrate with tidygeocoder

### ISSUE THREAD

**Issue by freyfogle** [ropensci/opencage#110]
see: https://jessecambon.github.io/tidygeocoder/index.html

Perhaps it is easy to integrate the opencage package into tidygeocoder?

Probably best to first release the new version. What is the best way for me to help make that happen?

**Comment by dpprdan** [comment]
AFAICT tidygeocoder does not integrate existing packages, but relies on custom code for each geocoder. See [this guide](https://github.com/jessecambon/tidygeocoder/issues/34#issuecomment-660204164) to add support for another geocoder.

**Comment by freyfogle** [comment]
fair enough, wasn't aware.

**Comment by dpprdan** [comment]
https://github.com/jessecambon/tidygeocoder/pull/69
