### ISSUE TITLE
Docs fail to build opencage.Rmd

### ISSUE THREAD

**Issue by jeroen** [ropensci/opencage#112]
Docs fail to build:

```
Quitting from lines 41-47 (opencage.Rmd) 
Error : HTTP failure: 401
```

See https://dev.ropensci.org/blue/organizations/jenkins/opencage/detail/opencage/103/pipeline

**Comment by dpprdan** [comment]
> Finished: SUCCESS

https://dev.ropensci.org/blue/organizations/jenkins/opencage/detail/opencage/106/pipeline/

**Comment by jeroen** [comment]
Thanks! --> https://docs.ropensci.org/opencage
