### ISSUE TITLE
Release opencage 0.2.0

### ISSUE THREAD

**Issue by dpprdan** [ropensci/opencage#120]
Prepare for release:

* [x] `devtools::build_readme()`
* [x] Check [current CRAN check results](https://cran.rstudio.org/web/checks/check_results_opencage.html) (just a note re vignette title, which have been rewritten)
* [x] `devtools::check(remote = TRUE, manual = TRUE)`
* [x] `devtools::check_win_devel()`
* [x] `rhub::check_for_cran()`
* [x] `revdepcheck::revdep_check(num_workers = 4)`
* [x] Update `cran-comments.md` (add comment re: `<<-`?)
* [x] [Polish NEWS](https://style.tidyverse.org/news.html#news-release)

Submit to CRAN:

* [x] email CRAN re. maintainer change
* [ ] Draft blog post (#56)
* [x] `usethis::use_version('minor')`
* [x] `devtools::submit_cran()`
* [x] Approve email

Wait for CRAN...

* [x] Accepted :tada:
* [x] `usethis::use_github_release()`
* [x] `usethis::use_dev_version()`
* [ ] Finish blog post
* [ ] Tweet
* [ ] Add link to blog post in pkgdown news menu

**Comment by freyfogle** [comment]
amazing, have to admit I wasn't sure this day would come. Congrats!

**Comment by freyfogle** [comment]
just to add, we will of course do a blog post as well. If you like happy to do it in interview format, where you explain things. Up to you. Regardless, allow me to once again say thanks for all your efforts. It is much appreciated.

**Comment by maelle** [comment]
@dpprdan we need to add an item where I first email about the maintainer change

**Comment by maelle** [comment]
https://stackoverflow.com/questions/39223320/transferring-maintainership-of-an-r-package-on-cran/39224965#39224965

**Comment by maelle** [comment]
See also https://devguide.ropensci.org/changing-maintainers.html#taking-over-maintenance-of-a-package
