### ISSUE TITLE
Add package version to user-agent string

### ISSUE THREAD

**Issue by dpprdan** [ropensci/opencage#124]
> Please use a unique user-agent string, so we can see how different libraries are being used and more easily identify the source of any problems. Ideally the user-agent string should include the version number of your library.

https://opencagedata.com/guides/how-to-write-an-sdk-for-the-opencage-api

Use `packageVersion("opencage")`

Maybe don't want to call `packageVersion` every time we make a request, i.e. pass a fixed string to oc_get instead.
https://github.com/ropensci/opencage/blob/0196657c379ffff3886b525b661cccf648ef48de/R/utils.R#L105-L111

**Comment by maelle** [comment]
well maybe we can memoise packageVersion in this case? :-)

**Comment by dpprdan** [comment]
Maybe this is one of the rare occasions where having a variable that is set at build-time is okay?

**Comment by maelle** [comment]
oh, right, sounds interesting
