### ISSUE TITLE
CRAN error w.r.t. `no_annotation`

### ISSUE THREAD

**Issue by dpprdan** [ropensci/opencage#158]
From Kurt Hornik via email:

> Please see the problems shown on
> <https://cran.r-project.org/web/checks/check_results_opencage.html>.
> 
> Please correct before 2024-07-02 to safely retain your package on CRAN.

<details>
<summary>Error</summary>

```r
Check Details

Version: 0.2.2
Check: tests
Result: ERROR
    Running ‘testthat.R’ [10s/15s]
  Running the tests in ‘tests/testthat.R’ failed.
  Complete output:
    > library(testthat)
    > 
    > test_check("opencage")
    Loading required package: opencage
    [ FAIL 2 | WARN 0 | SKIP 33 | PASS 227 ]
    
    ══ Skipped tests (33) ══════════════════════════════════════════════════════════
    • On CRAN (12): 'test-oc_api_ok.R:2:3', 'test-oc_check_status.R:4:3',
      'test-oc_check_status.R:38:3', 'test-oc_check_status.R:49:3',
      'test-oc_check_status.R:60:3', 'test-oc_check_status.R:71:3',
      'test-oc_clear_cache.R:2:3', 'test-oc_forward.R:69:3', 'test-oc_get.R:4:3',
      'test-oc_get.R:60:3', 'test-oc_get.R:71:3', 'test-oc_reverse.R:60:3'
    • OpenCage API key is missing (21): 'test-deprecated.R:68:3',
      'test-deprecated.R:89:3', 'test-oc_check_status.R:15:3',
      'test-oc_forward.R:29:3', 'test-oc_forward.R:39:3', 'test-oc_forward.R:56:3',
      'test-oc_forward.R:78:3', 'test-oc_forward.R:92:3',
      'test-oc_forward.R:116:3', 'test-oc_forward.R:128:3',
      'test-oc_forward.R:186:3', 'test-oc_forward.R:194:3', 'test-oc_get.R:22:3',
      'test-oc_get.R:41:3', 'test-oc_process.R:118:3', 'test-oc_reverse.R:18:3',
      'test-oc_reverse.R:28:3', 'test-oc_reverse.R:45:3', 'test-oc_reverse.R:70:3',
      'test-oc_reverse.R:94:3', 'test-oc_reverse.R:109:3'
    
    ══ Failed tests ════════════════════════════════════════════════════════════════
    ── Failure ('test-deprecated.R:41:3'): opencage_forward/opencage_reverse return what they should
              with several parameters. ──
    sum(grepl("annotation", names(results[["results"]]))) not equal to 0.
    1/1 mismatches
    [1] 1 - 0 == 1
    ── Failure ('test-deprecated.R:60:3'): opencage_forward/opencage_reverse return what they should
              with several parameters. ──
    sum(grepl("annotation", names(results[["results"]]))) not equal to 0.
    1/1 mismatches
    [1] 1 - 0 == 1
    
    [ FAIL 2 | WARN 0 | SKIP 33 | PASS 227 ]
    Error: Test failures
    Execution halted
Flavor: [r-devel-linux-x86_64-debian-clang](https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-debian-clang/opencage-00check.html)
``` 

</details>

Fails (until now) for all R devel flavours, but also for oldrel (R 4.3.3) on Windows.

I am on it.

**Comment by dpprdan** [comment]
First hunch: could be that the API response changed (i.e. an annotation field is returned even though `no_annotation` is requested).

Also, if this test makes an API request, it probably shouldn't run on CRAN.

**Comment by freyfogle** [comment]
Hi, happy to try to help you debug, but I dont understand all the R test output. 
Nothing has (intentionally) changed at OpenCage. 

what is the exact request causing the failure?

**Comment by freyfogle** [comment]
Wait, I think we do have a bug on our side. Working on a fix now

**Comment by dpprdan** [comment]
I am pretty sure my hunch was right, but that was just the trigger for the problem to surface here. The real problem is that the test is misspecified, because [it is executed with](https://github.com/ropensci/opencage/blob/7b8060891c411f869f0d7386afcdb5e7ac58c451/tests/testthat/test-deprecated.R#L26) the [200 testing key](https://opencagedata.com/api#testingkeys), which ignores most (if not all?) other query parameters. Using that key to test query parameters is therefore nonsense. 

@freyfogle I think this did not cause a problem before because the response to [a query with the 200 testing key](https://api.opencagedata.com/geocode/v1/json?key=6d0e711d72d74daeb2b0bfd2a5cdfdba&q=52.3877830%2C+9.7334394&pretty=1&no_annotations=1) (this is the query linked [in the docs](https://opencagedata.com/api#testingkeys)), did not contain `annotations`, but now it does (`annotations.pips: 0`). If it had before, the CRAN tests would have thrown an error. Note that the query URL contains `no_annotations=1`, so I guess there really shouldn't be any annotations? (That's probably the bug you're referring to?)

**Comment by dpprdan** [comment]
> Using that key to test query parameters is therefore nonsense.

So that test should run with a real key and (therefore) skipped on CRAN.

**Comment by freyfogle** [comment]
correct, there should not be any annotation. Fix will be live in about 15 minutes.

**Comment by freyfogle** [comment]
ok, fix is now live and I believe this will again be passing.

So sorry for the problems, was entirely unintended. We are now adding tests to ensure this doesn't happen again

**Comment by dpprdan** [comment]
No worries! A welcome nudge to look into this again.

> the [200 testing key](https://opencagedata.com/api#testingkeys), which ignores most (if not all?) other query parameters

@freyfogle A query with this key only ignores the query string (i.e. the `q` parameter), correct? 

If so, using that key to test the other parameters might not have been such a nonesense idea after all (because that would work on CRAN). (Whether it is a good idea to make requests from CRAN to a live API is another issue w.r.t. to possibly failing tests because the API is down. Then again, this apparently worked for 3+ years now).

**Comment by freyfogle** [comment]
Yes, the 200 testing key simply replaces the query with `51.952659,7.632473` regardless of what was specified. 

I have no idea what the norms are for CRAN in terms of doing "live" tests, but obviously we work very hard so that the API is never down. See [our annual uptime reports](https://blog.opencagedata.com/tagged/uptime).

**Comment by dpprdan** [comment]
I sent an e-mail to CRAN that all checks pass again and received a confirmation from Kurt:

>  Confirmed, you're all good again.

**Comment by dpprdan** [comment]
I sent another e-mail yesterday, re the "[issues need fixing before 2024-07-02]" label still showing on https://cran.r-project.org/package=opencage. No reply yet.
