### ISSUE TITLE
use NEWS, git tags, and releases

### ISSUE THREAD

**Issue by sckott** [ropensci/opencage#17]
hey @masalmon  - We want all rOpenSci pkgs to consistently keep track of changes, following https://github.com/ropensci/onboarding/blob/master/packaging_guide.md#-news  
- use a `NEWS` or `NEWS.md` file to keep track of changes with each version released to CRAN
- git tag each CRAN version
- use the [releases tab](https://github.com/ropenscilabs/opencage/releases) on this repo to include the associated NEWS items for each tag/version

Can you please do the three above items from now on?

**Comment by maelle** [comment]
Thanks @sckott, from now on (one month later... sorry about that!) I'll do this.
