### ISSUE TITLE
support no_record=1 param

### ISSUE THREAD

**Issue by freyfogle** [ropensci/opencage#18]
FYI, not sure if you saw (or if any changes are needed) but a few weeks back we added a new "no_record" parameter.

http://blog.opencagedata.com/post/145602604628/more-privacy-with-norecord-parameter

**Comment by maelle** [comment]
Oh nice, I'll add this soon!

**Comment by freyfogle** [comment]
no rush at all from our side, just wanted to make you aware.

**Comment by maelle** [comment]
Thanks @freyfogle. Nice new option! :+1:
