### ISSUE TITLE
Namibia country code

### ISSUE THREAD

**Issue by knapply** [ropensci/opencage#24]
I want to thank everyone who worked on this handy, dandy package that I've been playing with. So far it's an incredibly convenient way of dealing with messy addresses for which other solutions have been inadequate. I'm very grateful.

It's easy to work around, but as an FYI:
Namibia's country code is set to `NA` (as in not available) instead of the character `"NA"`
````
> opencage_forward(placename = "Windhoek,Namibia",  countrycode = "NA", no_annotations = TRUE)
# Error: countrycode does not have a valid value.

> opencage::countrycodes %>% filter(is.na(Code))
# # A tibble: 1 x 1
#    Code
#   <chr>
# 1  <NA>

````

**Comment by maelle** [comment]
Oops, thanks, will try to have a look ASAP!

**Comment by maelle** [comment]
The new CRAN version fixes this thanks to @dpprdan! 🎉
