### ISSUE TITLE
Add github topics?

### ISSUE THREAD

**Issue by dpprdan** [ropensci/opencage#26]
as in
![grafik](https://user-images.githubusercontent.com/1423562/35780670-4c9116fc-09df-11e8-914b-eb1367167358.png)

**Comment by maelle** [comment]
very good point, now done. I was being lazy about it because I hope to get an automatic way to add them based on well-organized package metadata, see https://github.com/ropensci/codemetar/issues/49

**Comment by freyfogle** [comment]
The bad programmer says "I could just do this manually".
The good programmer says "I could automate this".
The great programmer says "I should just do this manually".
