### ISSUE TITLE
Add user-agent to httr::GET

### ISSUE THREAD

**Issue by dpprdan** [ropensci/opencage#28]
See #27 

```r
ua <- user_agent("http://github.com/ropensci/opencage")
resp <- GET(url, ua)
```
httr [vignette](https://cran.r-project.org/web/packages/httr/vignettes/api-packages.html): "Set a user agent"

**Comment by dpprdan** [comment]
This is now in devel. 
@freyfogle If you like, you could check in your API logs to confirm if it works? I only made a few calls last night though, so maybe wait a couple of days?

**Comment by maelle** [comment]
cf #37 too

**Comment by freyfogle** [comment]
Hi, I can confirm we are now seeing this user-agent string in our logs. Nice work, thanks.

**Comment by dpprdan** [comment]
Just a heads up: @maelle changed the user-agent string to "opencage-R" in bc6944d.

**Comment by freyfogle** [comment]
good to know. makes no difference to us as long as it stays consistent

**Comment by maelle** [comment]
I'm not even sure I _changed_ it and didn't _remove_ it temporarily because `crul` docs were not 100% clear/foolproof but I'm [investigating this](https://github.com/ropensci/crul/issues/63) and will update the thread. 😸

**Comment by maelle** [comment]
@dpprdan so now it works, but it's called "opencage-R". Am open to changing it back to the previous string, I'll let you decide and then we'll keep it forever. 😺

**Comment by dpprdan** [comment]
@maelle I know I am nit-picking, but actually I do prefer the repo url, since makes clear how to reach us. So I'll take you up on your offer. 😼

**Comment by maelle** [comment]
Perfect! 😀
