### ISSUE TITLE
Collaborator access

### ISSUE THREAD

**Issue by maelle** [ropensci/opencage#30]
https://help.github.com/articles/permission-levels-for-a-user-account-repository/#collaborator-access-on-a-repository-owned-by-a-user-account

@dpprdan could create the devel branch but not push to it.

**Comment by maelle** [comment]
Ah I was looking at the wrong webpage https://help.github.com/articles/repository-permission-levels-for-an-organization/

**Comment by maelle** [comment]
I created a team with this repo as assigned repo and invited both @dpprdan and @jessesadler to it (after removing them as collaborators from this repo).

**Comment by dpprdan** [comment]
@maelle Have you created the team already? I have not gotten an invitation yet and also cannot push. (Wondering whether pushing is actually a safe way to collaborate here or whether PRs would be better. How do you do this @ropensci or in your other projects?)

**Comment by maelle** [comment]
It tells me you have a pending invitation to the team (Jesse got and accepted his). I'll revoke it and invite you again.

I think pushing to the devel branch is perfect, but yes with PR we can all comment on it (that said if we discuss things well in the issues you've opened, the reviews will be quick).

**Comment by maelle** [comment]
I don't think we have guidelines on this but I'll make a note to add guidance to our packaging guide, good point!

**Comment by dpprdan** [comment]
Still no invite. Is there anything I can do? I don't even know where to look.
I.e. no invite for the team. I had one yesterday for the collaborator thing (personal repo) and accepted it. That allowed me to create the devel branch, but not push to it.

**Comment by maelle** [comment]
And I can't find an invite link, I can only update or cancel the invitation. I think you should have gotten an email. Maybe look in notifications too? 

@jessesadler where did you get the invitation?

**Comment by jessesadler** [comment]
Yes. I received an email and was able to click on the link from there.

**Comment by dpprdan** [comment]
aaah! "check your e-mail" did the trick. *self-facepalm*
Sorry for my confusion!

**Comment by maelle** [comment]
No problem! This issue started with my confusion and ended with yours but now everyone has the necessary access rights I think. 🎉

**Comment by dpprdan** [comment]
Well... still cannot push. 

``git -c diff.mnemonicprefix=false -c core.quotepath=false push -v --tags --set-upstream upstream devel:devel
remote: Permission to ropensci/opencage.git denied to dpprdan.
fatal: unable to access 'https://github.com/ropensci/opencage.git/': The requested URL returned error: 403
Pushing to https://github.com/ropensci/opencage.git``

Giving up for now, will try to resolve this again later.

**Comment by maelle** [comment]
@sckott if I give someone write access to the repo via a team they should be able to push right?

**Comment by maelle** [comment]
@dpprdan do you still have this issue?

Is your local repo a clone of this repo or of your own?

**Comment by dpprdan** [comment]
No, seems to work now. Did you change anything?

**Comment by maelle** [comment]
No but excellent news!

**Comment by dpprdan** [comment]
Interesting, because on the [Team > Repositories](https://github.com/orgs/ropensci/teams/opencage/repositories) page the "Write" button is greyed out for me. I would have thought that this is the place where one can view the priviliges. 
Oh wait, it's greyed out because I am not a Team Admin, but it shows that I have Write access?! So much to learn... 😆

**Comment by maelle** [comment]
I think it's greyed because you're not an admin so you can't change it. "Write" means that team members can read, clone and push to the repository.

[Here](https://github.com/orgs/ropensci/teams/opencage/members) you can see I am maintainer and you and Jesse members.

I am learning too because I had never created a team for such a case. 😀
