### ISSUE TITLE
ratelimit API calls

### ISSUE THREAD

**Issue by dpprdan** [ropensci/opencage#32]
use ratelimitr on httr::GET (and after memoise, i.e. memoise -> ratelimit -> GET)

**Comment by dpprdan** [comment]
The default limit is set to 1 call per second as per the [API limit](https://geocoder.opencagedata.com/pricing) for the Free Trial package. It can be configured with setting `options("oc_requests_per_second")` at the start of a session/script or permanently via `.Rprofile`.

**Comment by maelle** [comment]
Cool, thx a lot. In the vignette documenting this we can show code example and mention `usethis::edit_r_profile` as a way to easily find where the .Rprofile is/open it.
