### ISSUE TITLE
add tests for oc_forward and oc_reverse

### ISSUE THREAD

**Issue by dpprdan** [ropensci/opencage#36]
Maybe use [httptest](http://enpiar.com/r/httptest/index.html) package as well? This can also be used for [vignettes](http://enpiar.com/r/httptest/articles/vignettes.html).

**Comment by maelle** [comment]
Or maybe the occasion for me to try https://github.com/ropensci/webmockr ☺

**Comment by dpprdan** [comment]
See also #48

**Comment by dpprdan** [comment]
closing this in favour of #48
