### ISSUE TITLE
Ditch httr in favour of crul

### ISSUE THREAD

**Issue by maelle** [ropensci/opencage#37]
I'd like to ditch ` httr` in favour of `crul`. This way we could use `webmockr` as well (part of the @sckott -verse)

It wouldn't be too much work since for the simple requests here using `crul` is no rocket science. I use it in http://github.com/ropensci/ropenaq now and at the time the difficulty was understanding asynchronous requests which we wouldn't need here.

@dpprdan @jesssadler would you be up for learning `crul`? Otherwise I can do the translation, this doesn't change the design which you both work on.

After `opencage` next release then an rOpenSci blog post (or 2) about making a package user-friendlier + testing it better would be interesting I think 🤔

**Comment by dpprdan** [comment]
Apart from your enthusiastic blob post, I don't really know crul? What does it do better than httr (apart from async requests, which is not relevant here)? I'm open to it, but don't see the benefit, yet.

**Comment by maelle** [comment]
It works with `webmockr` ☺

**Comment by sckott** [comment]
it will also work with `vcr` very soon to cache http requests for test suites

**Comment by dpprdan** [comment]
Isn't that what httptest does (as well)? But I don't really know what I am talking about, so, yeah, go ahead. 😄

**Comment by maelle** [comment]
I do have a bias for rOpenSci tools 😂

**Comment by jessesadler** [comment]
I have no real opinion or any expertise in this issue. Trying to learn as much as I can about this stuff, but I am not too far yet. ☺️
