### ISSUE TITLE
add json/geojson output option

### ISSUE THREAD

**Issue by dpprdan** [ropensci/opencage#38]
We currently use the JSON endpoint, but the [API](https://geocoder.opencagedata.com/api#forward-resp) can also return GeoJSON output.
@maelle Would that be handy for your jqr [idea](https://github.com/ropensci/opencage/issues/27#issuecomment-364890635)?
Might also be easier to convert to sf objects, though data.frame to sf conversion is also [easy](https://github.com/ropensci/opencage/issues/27#issuecomment-364998636).
Pelias always seems to return GeoJSON btw, which is why rmapzen::mz_search can easily provide it and sf::st_read("url_to_api") works, like [this](https://twitter.com/MikeTreglia/status/962479758327078912) for example.
sf::st_read(URLencode("https://api.opencagedata.com/geocode/v1/geojson?q=Elbphilharmonie+Hamburg&key=OPENCAGE_KEY"))

**Comment by jessesadler** [comment]
The option of going through sf_read is interesting, but I have been able to use the output of the data frame with multiple responses to pipe to create an sf object and then to mapview.

**Comment by maelle** [comment]
Just a notw to myself to look whether the `geojsonio` package is relevant here

**Comment by jessesadler** [comment]
@maelle I was just looking at `geojsonio`, but it looks like it is mostly for converting to GeoJSON and not from GeoJSON.

**Comment by maelle** [comment]
What about we have three output formats:

* data.frame

* JSON (and I could add a vignette about `jqr` use)

* GeoJSON (and @dpprdan could add a vignette about `sf` use)

**Comment by maelle** [comment]
Oh and in the case of three output formats I'd be in favour of a completely flat data.frame (because users who want list columns could use examples from a vignette about JSON).

**Comment by dpprdan** [comment]
👍 to both. My plan is to add a GeoJSON option to `oc_forward()`. There does [not exist](https://geocoder.opencagedata.com/api#reverse-resp) a GeoJSON endpoint for reverse.

**Comment by freyfogle** [comment]
wow, well spotted. There is in fact also a geojson response for reverse. just change `json` to `geojson` in the request URL (in fact, we have only a single endpoint - the distinction between forward and reverse is for humans, on our side all requests look the same. Not having a geojson example for reverse an oversight in the docs, I will look to get it added. That said, geojson is about 1% of our requests.

**Comment by dpprdan** [comment]
Not when we are done anymore, it isn't. 😉

**Comment by freyfogle** [comment]
honestly we have debated dropping support for it (and for XML actually). It is not clear that it is valued by anyone and it is one more thing to maintain. GeoJSON definitely has it's uses, but not clear that this is one of them. No customer has ever asked about it.

**Comment by dpprdan** [comment]
We added this to `oc_forward` and `oc_reverse`, but now that I am reading this again I am wondering whether you meant "don't do this, we'll drop this soon" or rather "it's fine if you do that, just know that we might drop GeoJSON support some time in the future", @freyfogle?

**Comment by freyfogle** [comment]
sorry, I should have been more clear. GeoJSON and XML fall into the "it's fine if you do that, just know that we might drop support some time in the future", but we would give at least 3-6 months of notice.

**Comment by dpprdan** [comment]
@freyfogle 👍 & Thanks!  This is done, then.
