### ISSUE TITLE
Support multiple country codes

### ISSUE THREAD

**Issue by dpprdan** [ropensci/opencage#44]
opencagedata supports \[multiple country codes(<https://geocoder.opencagedata.com/api#forward-opt>), but opencage 📦  does not (yet).

``` r
# French territories according to the opencage website
french_territories <- 
  c("fr", "bl", "gf", "gp", "mf", "mq", "nc", "pf", "pm", "re", "tf", "wf", "yt") %>% 
  toupper()

opencage_forward("Arc de Triomphe de l’Etoile, Paris", countrycode = french_territories)
#> Warning in if (!(countrycode %in% countrycodes$Code)) {: the condition has
#> length > 1 and only the first element will be used
#> Error in vapply(elements, encode, character(1)): values must be length 1,
#>  but FUN(X[[2]]) result is length 13
```

**Comment by maelle** [comment]
I think it now works. For the record the example above doesn't return any result, unless one removes "de l'Etoile".

**Comment by dpprdan** [comment]
👍 Could you please add a keyword or two to your commit messages, otherwise one always has to go to Github (from e.g. RStudio) to see what the issue was about?

**Comment by maelle** [comment]
will do!

**Comment by maelle** [comment]
(I mean in the future, for now I won't rename the old ones)

**Comment by dpprdan** [comment]
Thanks! 
Re future: of course. Wait, that's possible? (Without rewriting history and getting everybody mad at you?) I mean, in principle, not that you ought to do it.

**Comment by maelle** [comment]
I have no idea, I just _imagine_ it is? Or maybe not? 🤔 (I won't try to mess up with this repo but might look into it one day!)
