### ISSUE TITLE
supply encoding to crul parse()

### ISSUE THREAD

**Issue by dpprdan** [ropensci/opencage#45]
I get a warning "No encoding supplied: defaulting to UTF-8.". This is due to `req$parse()` in `oc_parse()`, which has an encoding parameter with default "unknown". I guess it is safe to assume that opencagedata will always return "UTF-8"?! I wouldn't know how to check, anyways.
So just modify it like this:
`text <- req$parse(encoding = "UTF-8")`

**Comment by jessesadler** [comment]
I am getting the same warnings and figured it must be something like that.

**Comment by sckott** [comment]
note that's the same behavior as `httr`, to not have a default encoding when parsing text, but instead make the user supply it
