### ISSUE TITLE
tibble as a dependency

### ISSUE THREAD

**Issue by jessesadler** [ropensci/opencage#49]
I have been working on the `oc_forward_df` and `oc_reverse_df` functions a bit more. I am returning everything as a data frame. The original `opencage_format` returns the results as a tbl_df, but it uses `dplyr::tbl_df`, which is deprecated and the documents say to use `tibble::as_tibble`. I prefer the tibble output, but wanted to see what @maelle and @dpprdan think.

**Comment by maelle** [comment]
I agree! 👌

**Comment by dpprdan** [comment]
Me too!

**Comment by jessesadler** [comment]
Nice. My console will be a lot happier place with tibble printing method than with data.frame

**Comment by maelle** [comment]
I'll close this since we all agree on adding `tibble` as a dependency. 😸
