### ISSUE TITLE
Blog post documenting the new version

### ISSUE THREAD

**Issue by maelle** [ropensci/opencage#56]
Maybe as tech note for rOpenSci tech note blog?

Or a longer one for rOpenSci blog itself, that could also document how you two got involved @dpprdan @jessesadler and how you've shared and organized work. "More user-friendliness and taking the 🚌 factor into account" for instance :grinning:

**Comment by freyfogle** [comment]
Will also do a blog post on the OpenCage blog whenever you are ready. Could be a general announcement or if you prefer an interview with one of you. Just let me know once you are ready.

**Comment by maelle** [comment]
sounds great to announce it in both places, thanks! 👌 Plus it'd be a good opportunity to advertise for rOpenSci, in particular the peer review system. 😀

**Comment by freyfogle** [comment]
I think this issue can be closed, [the blog post](https://blog.opencagedata.com/post/new-r-packages-for-accessing-the-opencage-geocoding-api) was published almost 18 months ago 😀
