### ISSUE TITLE
new OpenCage website URL

### ISSUE THREAD

**Issue by freyfogle** [ropensci/opencage#59]
Hola,

FYI - today we moved the opencage website. it is now here:
https://opencagedata.com

The API URL has not changed, just the website. 
The old website URLs will redirect, but perhaps in the new release things could point to the new URLs?

What is the status on the v2?  If someone points me to the correct branch I am happy to submit a pull request with updated URLs.

as ever, many thanks for your efforts,
Ed

**Comment by dpprdan** [comment]
Hola and thanks Ed, for letting us know. Do I see correctly that you just dropped the `geocoder` subdomain?

In general vO.2 still lives in the `devel` branch. I've been working on and off (more off TBH) on the package, though, and jumping from rabbit hole to rabbit hole, so there are some newer changes in my repo and there is even some stuff that I have not committed yet 😨. So I guess this is a good opportunity to do that and I will make the URL changes while I am at it.

**Comment by freyfogle** [comment]
yes, we removed the geocoder portion of the URL, so the change should be trivial. 

re: v0.2 - my advice is dont let perfect be the enemy of good. Thank you for all your work, we appreciate it.

**Comment by dpprdan** [comment]
> re: v0.2 - my advice is dont let perfect be the enemy of good.

WHAAAT? No idea what you're talking about... 😉

**Comment by freyfogle** [comment]
Hi everyone,

FYI two more new things: 

1. we added a new optional parameter: `proximity`
https://blog.opencagedata.com/post/new-optional-parameter-proximity

2. a new annotation - FIPS codes:
https://blog.opencagedata.com/post/new-annotation-fips

Anything I can do to help get the v2 library out?

hope you're having a great summer:
Ed

**Comment by dpprdan** [comment]
Thanks Ed! I saw both new things on twitter and made a mental note to include both, but this is a good reminder to open issues for those. I am only vaguely familiar with FIPS codes, so my idea was to mention them in the annotations section of a vignette. Or did you have a different idea in mind about how we should present them? 

Re v2, sorry that I am blocking this at the moment. I am clearly not handling this well. FWIW I am working on enabling multiple (serial) requests with different `bounds`, `country`- and `languagecodes`. I think I layed the groundwork with the `bounds` feature that will help to incorporate the `proximity` parameter fairly quickly. I will be on vacation the next two weeks but am aiming to make something visible in the second half of August, so we can get the next version out soon-ish.

**Comment by maelle** [comment]
I'll tell Slackbot to remind me to check here again in 2 weeks 🙂

**Comment by maelle** [comment]
Well, 3 weeks.

**Comment by freyfogle** [comment]
re: FIPS codes, I would just present them as you do all the other annotations. I do not think anything special is required. One thing - we of course only return FIPS codes if the location is in the US.

re: multiple serial requests - I would get the basics working first, then add more functionality. Good now is better than perfect at some indefinite time in the future. Totally up to you of course though.

As always, thanks for your efforts!

enjoy your holiday,
Ed

**Comment by freyfogle** [comment]
Hi everyone, 

I don't mean to alarm any of you, but the MATLAB people are moving faster! 
We now have a MATLAB tutorial https://opencagedata.com/tutorials/geocode-in-matlab

How do we get the v2 across the finish line? What can I/we do to help?

**Comment by jessesadler** [comment]
Yes. Things have definitely slowed down, and I have not looked at things in a while. However, I am hoping to dive back into the project in the next couple of weeks and try to push the release over the line. How are things on your side @dpprdan?

**Comment by freyfogle** [comment]
Friends,

something is keeping us from getting the new version live. What is it? 
How can I help solve it?

If motivation is needed, perhaps it would help if I offered to donate €200 to any charity of your choice on the day the new version goes live? It could be something R related, or something else. 
Or if you prefer happy to split the money between you three. Whatever it is you all can agree on (though please don't start a new issue to debate where the money should go).

Thanks for your efforts and please let me know

**Comment by dpprdan** [comment]
The main issue, the website URL, is fixed in devel, for proximity see #60, for FIPS codes #53.
