### ISSUE TITLE
create pkgdown website

### ISSUE THREAD

**Issue by maelle** [ropensci/opencage#68]
deployed from Travis, with `run_dont_run=TRUE`.

**Comment by maelle** [comment]
no need to since there's the central building of websites (docs.ropensci.org, dev.ropensci.org) now but I'll let this open until there's a way to provide an API key + options to the build.

**Comment by maelle** [comment]
@jeroen one cannot use an API key for the docs server yet, correct?

**Comment by dpprdan** [comment]
Jeroen wrote on a related issue on ropensci Slack: 

> We don’t support secret variables (yet?). There is no straight forward and secure way to do this in jenkins. So for now, it’s best to [...] pre-render your vignettes locally. [...]
> For example in jsonlite we pre-render two vignettes that require auth: https://github.com/jeroen/jsonlite/blob/master/vignettes/precompile.R
> So the ‘real’ vignettes is called `.orig` and then you locally run the script to generate the `Rmd` with the R already rendered.

A slightly different approach (incl. PDF vignettes) has been mentioned over at https://github.com/r-lib/pkgbuild/issues/58#issuecomment-559791789

**Comment by dpprdan** [comment]
[How to precompute package vignettes or pkgdown articles](https://ropensci.org/technotes/2019/12/08/precompute-vignettes/)

**Comment by dpprdan** [comment]
We precompute vignettes as of #113/#114. pkgdown website is on [docs.ropensci.org/opencage](https://docs.ropensci.org/opencage) (master branch).
