### ISSUE TITLE
return status message from API on errors

### ISSUE THREAD

**Issue by maelle** [ropensci/opencage#69]
To not only return error http code, but also a definition to go with it https://github.com/sckott/httpcode

**Comment by freyfogle** [comment]
I recommend instead you display the `message` we return in the `status` portion of the response.  It provides more specific debugging information. for example an HTTP 400 response means "invalid request" but our message is more specific, for example "invalid coordinates" or "invalid format". I think it helps users discover the real problem more quickly.

**Comment by dpprdan** [comment]
@maelle You already implemented those back in the day. With #75 I get

``` r
library(opencage)

# keys from https://opencagedata.com/api#codes or
# https://github.com/OpenCageData/opencagedata-misc-docs/blob/master/library-guidelines.md # nolint
key_402 <- "4372eff77b8343cebfc843eb4da4ddc4" # always returns a 402 responce
key_403 <- "2e10e5e828262eb243ec0b54681d699a" # always returns a 403 responce

oc_reverse(latitude = 0, longitude = 0, key = key_402)
#> Error: HTTP failure: 402
#> Valid request but quota exceeded (payment required)

oc_reverse(latitude = 0, longitude = 0, key = key_403)
#> Error: HTTP failure: 403
#> Forbidden (API key blocked)

some_random_key <- "qhgrojbhmibfyucsocxsmzdlpkrwcdwr"

oc_forward("Paris", key = some_random_key)
#> Error: HTTP failure: 401
#> Unable to authenticate - missing, invalid, or unknown API key
```

**Comment by dpprdan** [comment]
@freyfogle Just FYI: The text of the status messages mentioned in the [documentation](https://opencagedata.com/api#codes) do not fully match those returned by the API, at least for the 402 response. I [get "quota exceeded" from the API](https://api.opencagedata.com/geocode/v1/json?q=Barcelona&key=4372eff77b8343cebfc843eb4da4ddc4) and in the docs it says "Valid request but quota exceeded (payment required)".

**Comment by dpprdan** [comment]
@maelle Like you said (#75), we should return the status messages from the API instead of storing them as external data in the package. That way we are always in sync with the API's status messages.

**Comment by freyfogle** [comment]
> @freyfogle Just FYI: The text of the status messages mentioned in the [documentation](https://opencagedata.com/api#codes) do not fully match those returned by the API, at least for the 402 response. I [get "quota exceeded" from the API](https://api.opencagedata.com/geocode/v1/json?q=Barcelona&key=4372eff77b8343cebfc843eb4da4ddc4) and in the docs it says "Valid request but quota exceeded (payment required)".

yes, they may be slightly different for brevity. Not a bug.

**Comment by freyfogle** [comment]
Thanks for making me aware our documentation here is unclear that the messages are not verbatim. A fix is going live now, screen shot attached
<img width="817" alt="Screenshot 2019-05-11 at 12 46 49" src="https://user-images.githubusercontent.com/351074/57568674-1ba7c780-73eb-11e9-992f-d108b5dd7c6a.png">
