### ISSUE TITLE
Add examples for oc_forward and oc_reverse in documentation

### ISSUE THREAD

**Issue by jessesadler** [ropensci/opencage#71]
Add examples for `oc_forward` and `oc_reverse`:

1. Examples of vectorized usage
2. Examples of vectorization of various arguments
	- [ ] multiple countrycodes (vectorised or not - e.g. french territories example on OC website)
3. Examples of `oc_forward_df` and `oc_reverse_df`, incl. unquoted column names
4. Examples of vectorization of various arguments with `oc_forward_df` and `oc_reverse_df`

**Comment by dpprdan** [comment]
Sorry, ~messed with~ added a bit to your issue description.
