### ISSUE TITLE
warn re API key with output = json_list, add_request = TRUE

### ISSUE THREAD

**Issue by dpprdan** [ropensci/opencage#74]
`stopifnot(!interactive())` (or equivalent) if `output = "json_list"` and `add_request = TRUE`

**Comment by charliejhadley** [comment]
I'd like to pose https://github.com/ropensci/opencage/pull/105 and https://github.com/ropensci/opencage/pull/106/files as a combined fix for this issue.

https://github.com/ropensci/opencage/pull/105 removes `add_request` as an argument as now all output types include the `oc_query` column. https://github.com/ropensci/opencage/pull/106/files now always scrubs URLs, unless the user explicitly calls `oc_show_key`

**Comment by dpprdan** [comment]
Closed with #116
