### ISSUE TITLE
new annotation in OpenCage API results "UN_M49"

### ISSUE THREAD

**Issue by freyfogle** [ropensci/opencage#78]
First up, wonderful to see all the progress on the new version. Please let me know if any way to help get it across the finish line. 

Secondly, there is now a new annotation in the OpenCage results that might be particularly relevant to users of R. We now return UN M49 codes ([blog post announcing this](https://blog.opencagedata.com/post/new-annotation-UN-M49-statistical-codes)) ([full docs](https://opencagedata.com/api#unm49)) that are often used in economic data analysis. This can tell you is a result is in a UN defined region like "sub-Saharan Africa" or in a "Least Developed Country (LDC)". 

I don't know if a new annotation requires any code changes in the R module, I would hope not, but just thought I should make you aware. If not of course please just close this issue.

Forward!

**Comment by maelle** [comment]
Thanks! It seems to already be included (using the dev version, and probably using master as well).

``` r
sarzeau <- opencage::oc_forward("Sarzeau", no_annotations = FALSE)
sarzeau[[1]]$UN_M49_regions_WORLD
#> [1] "001" "001"
sarzeau[[1]]$UN_M49_statistical_groupings
#> [[1]]
#> [1] "MEDC"
#> 
#> [[2]]
#> [1] "MEDC"
sarzeau[[1]]$UN_M49_regions_WESTERN_EUROPE
#> [1] "155" "155"
sarzeau[[1]]$UN_M49_regions_FR
#> [1] "250" "250"
sarzeau[[1]]$UN_M49_regions_EUROPE
#> [1] "150" "150"
```

<sup>Created on 2019-05-20 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

@dpprdan @jessesadler anything we want to do to process the output differently?

**Comment by dpprdan** [comment]
Indeed, it seems like we are already all set for this one. 🎉 
IMO the output is also fine as-is. 

When I tried to get the M49 values for a couple of countries ("Bolivia", "Bangladesh", "Belgium", "Botswana") I got the following error.

``` r
library("dplyr", warn.conflicts = FALSE)
library("opencage")

tibble(p = c("Bolivia", "Bangladesh", "Belgium", "Botswana")) %>% 
  oc_forward_df(p, no_annotations = FALSE, output = "all") %>% 
  select(p, starts_with("UN")) %>% 
  knitr::kable()
#> Error: Column `callingcode` can't be converted from character to integer
```

I don't fully understand yet why `character` cannot be converted to `integer` (`dplyr:::bind_rows_(x, .id)` is throwing an `Rcpp::exception`).

However, the API is indeed returning `callingcode` as an integer for e.g. [Bolivia](https://api.opencagedata.com/geocode/v1/json?q=Bolivia&limit=1&no_annotations=0&key=<<mykey>>) (`"callingcode":591`) but as a character for e.g. [Belgium](https://api.opencagedata.com/geocode/v1/json?q=Belgium&limit=1&no_annotations=0&key=<<mykey>>) (`"callingcode":"32"`). Is this something that could and should be fixed on the OpenCage API side, @freyfogle?

**Comment by freyfogle** [comment]
hmm, that's odd. will have a look, thanks for making me aware. More soon

**Comment by freyfogle** [comment]
ok, thanks for spotting this, very nice bug, it is now fixed, callingcode is now always a number. 
Feel free to close this issue

**Comment by dpprdan** [comment]
@freyfogle Sorry I missed another one the first time around. 
`"qibla":72.76` (Bolivia) vs `"qibla":"123.65"` (Belgium)
I checked the types of all returned results now, so this should be it (for the examples mentioned above at least).

**Comment by freyfogle** [comment]
hmm, thanks. Bizzare as I am not sure what about Belgium is causing this. Fix will be live in a few minutes

**Comment by dpprdan** [comment]
Bolivia is the outlier in this case compared to the other three.

**Comment by freyfogle** [comment]
ok, fix is now live, qibla should always be a number. Thanks again, very helpful.

**Comment by dpprdan** [comment]
🎉 
``` r
library("dplyr", warn.conflicts = FALSE)
library("opencage")
options(knitr.kable.NA = '')

tibble(p = c("Bolivia", "Bangladesh", "Belgium", "Botswana")) %>% 
  oc_forward_df(p, no_annotations = FALSE, output = "all") %>% 
  select(p, starts_with("UN")) %>% 
  knitr::kable()
```

<table>
<thead>
<tr class="header">
<th style="text-align: left;">p</th>
<th style="text-align: left;">UN_M49_statistical_groupings</th>
<th style="text-align: left;">UN_M49_regions_AMERICAS</th>
<th style="text-align: left;">UN_M49_regions_BO</th>
<th style="text-align: left;">UN_M49_regions_LATIN_AMERICA</th>
<th style="text-align: left;">UN_M49_regions_SOUTH_AMERICA</th>
<th style="text-align: left;">UN_M49_regions_WORLD</th>
<th style="text-align: left;">UN_M49_regions_ASIA</th>
<th style="text-align: left;">UN_M49_regions_BD</th>
<th style="text-align: left;">UN_M49_regions_SOUTHERN_ASIA</th>
<th style="text-align: left;">unknown</th>
<th style="text-align: left;">UN_M49_regions_BE</th>
<th style="text-align: left;">UN_M49_regions_EUROPE</th>
<th style="text-align: left;">UN_M49_regions_WESTERN_EUROPE</th>
<th style="text-align: left;">UN_M49_regions_AFRICA</th>
<th style="text-align: left;">UN_M49_regions_BW</th>
<th style="text-align: left;">UN_M49_regions_SOUTHERN_AFRICA</th>
<th style="text-align: left;">UN_M49_regions_SUB_SAHARAN AFRICA</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Bolivia</td>
<td style="text-align: left;">c(“LEDC”, “LLDC”)</td>
<td style="text-align: left;">019</td>
<td style="text-align: left;">068</td>
<td style="text-align: left;">419</td>
<td style="text-align: left;">005</td>
<td style="text-align: left;">001</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Bangladesh</td>
<td style="text-align: left;">c(“LDC”, “LEDC”)</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">001</td>
<td style="text-align: left;">142</td>
<td style="text-align: left;">050</td>
<td style="text-align: left;">034</td>
<td style="text-align: left;">Bangladesh</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Belgium</td>
<td style="text-align: left;">MEDC</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">001</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">056</td>
<td style="text-align: left;">150</td>
<td style="text-align: left;">155</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Botswana</td>
<td style="text-align: left;">c(“LEDC”, “LLDC”)</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">001</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">002</td>
<td style="text-align: left;">072</td>
<td style="text-align: left;">018</td>
<td style="text-align: left;">202</td>
</tr>
</tbody>
</table>

Maybe not the most useful table/column structure for this particular type of query, but I don't have a better idea for a general solution ATM.
