### ISSUE TITLE
Ask PRs to be directed to devel?

### ISSUE THREAD

**Issue by maelle** [ropensci/opencage#79]
Even after the next release?

**Comment by dpprdan** [comment]
What are you current thoughts on this, @maelle? I think I prefer a [GitHub flow model](https://guides.github.com/introduction/flow/) over a long running devel branch/git flow model.

**Comment by jessesadler** [comment]
I think GitHub flow moving forward would be good now that this major change to 0.2 is getting towards complete.

**Comment by maelle** [comment]
We have something with a dev branch for codemetar, with mistakes made once in a while. It might be more straightforward to PR to the default/master/main branch indeed

**Comment by dpprdan** [comment]
It seems we all lean away from a devel branch, so I am closing this.
